### PR TITLE
Code review request

### PR DESCRIPTION
**Pull request by shjang7**
For empty array input, all? method will return false

### CODE REVIEW

**Comment by shjang7** [comment]
Thanks for your reviewing my code.
Project description path : https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks
You can read this again.
This project aim for building those methods "each", "each with index", "select", "all?", ..., they didn't say to implement test file, but I added main.rb file for convinience. So, if you are not sure it is working or not, you can add more cases with your taste in "main.rb", if you want to get certain output, you could put some block for the input value with your taste as well.

For the our common understanding for "each" method, or "count" method, I will provide you those document below.
[ "each" method ]
each
It is the description for "each" method from ruby-doc.org
It was implemented with this method. (Implementing "my_each" method is the purpose of the project)
my_each_1
and if you wondering it is exact same working between "each" method and "my_each" method, you can see with building like this in main.rb. you can compare those easily.
my_each_2
my_each_3

[ "count" method ]
count
This description above is from ruby-doc.org
In the given block, "counts the number of elements for which the block returns a true value", so if the given block condition is only working for even number, it counts only even number as well.
This project is aim for implement "my_count" method below.
my_count_1
If you want to check it yourself it is working or not, you could see with adding this condition.
but implementing this test file was not included the project requirement, just for your convinience, because you want to see this kind of result for your test.
my_count_2

As I write above, you could test as much as you like to fit your taste, but the project aim for implement "numerable method" not the test file certain output only.
So please review again I implemented right "numerable method" in the "enumerable.rb" file.
If you need help for further testing regarding with this project, you could feel free to reach me through the slack(Suhyeon Jang)
Thank you.

**Comment by inhaq** [comment]
Hi @shjang7 thanks for commenting your thought process, I really appreciate the effort you're putting into it.

I'll add further details about `my_each`. If you look into the definition, it says to return array, not range from it.
For example, if i do compare test for `my_each` and `each`:
`expect([1,2,3].my_each { |i| i }).to eql([1,2,3].each {|i| i})` this should be true but it returns false in your case.

In `my_count` scenario, `my_count` should work without and with block as well, just how count works usually. 
For example:
`expect([1,2,3].my_count).to eql(3)` it returns error as no block given but for `count` it returns true.
Kindly look into it and I would be happy if you correct me if this is not the case.
Thanks 😊

**Comment by shjang7** [comment]
@inhaq Thank you for your detailed description.
I fixed "each", "count" method like below, and uploaded
[ each ]

[ count ]

Please review updated code again.
Thank you.

**Comment by shjang7** [comment]
Thank you @inhaq

**Pull request merged**
